added ukrainian language
aquaismissing/INCS2bot pull request #2
Opened 2023-08-14 23:04 UTC by akimerslys

2023-08-15 12:47 UTC, SyberiaK commented
Спасибо за помощь, будет вообще здорово, если добавишь несколько тегов в [tags.json](https://github.com/aquaismissing/INCS2bot/blob/master/l10n/data/tags.json).

2023-08-15 23:18 UTC, akimerslys commented
Добавил !

2023-08-16 21:33 UTC, Agent47Dev requested changes
На доработку

2023-08-16 21:33 UTC, Agent47Dev commented on l10n/data/uk.json
> +        "(суперник в броне / без броні)",
```suggestion
        "(противник/супротивник у броні / без броні)",
```
Я лично не могу определится как лучше будет, по этому открыт к дискусии

2023-08-16 21:33 UTC, Agent47Dev commented on l10n/data/uk.json
> +    "gun_origin_russia": "РоZZія",
```suggestion
    "gun_origin_russia": "Россія",
```
Я все прекрасно понимаю, но бот международный как бы....

2023-08-16 21:33 UTC, Agent47Dev commented on l10n/data/uk.json
> +        "[‎](https://telegra.ph/Detalnij-opis-08-14)ℹ️ Цей бот розроблений каналом @INCS2. Його код можна знайти за цим посиланням [GitHub](https://github.com/aquaismissing/INCS2bot).",
```suggestion
        "[‎](https://telegra.ph/Detalnij-opis-08-14)ℹ️ Цей бот розроблений каналом @INCS2. Програмний код можна знайти на [GitHub](https://github.com/aquaismissing/INCS2bot).",
```
Для простоты и укрощения будет лучше так написать

2023-08-16 21:33 UTC, Agent47Dev commented on l10n/data/uk.json
> +    "bot_feedback_text": "💬 Будь ласка напишіть нам ваші побажання та проблеми цього бота.",
```suggestion
    "bot_feedback_text": "💬 Будь ласка, росповiдь про Вашi **побажаннях** чи **проблемах**, з якими Ви зiткнулися пiд час використання ботом.",
```

2023-08-16 21:33 UTC, Agent47Dev commented on l10n/data/uk.json
> +        "Цей бот використовується для отримання інформації про стан серверів та перевірки онлайну Counter-Strike: Global Offensive та багато іншого.",
```suggestion
       "Цей бот призначенний для перевiрки кiлькостi гравцiв у онлайнi та доступнiсть серверiв Counter-Strike.",
```

2023-08-16 21:33 UTC, Agent47Dev commented on l10n/data/uk.json
> +    "currencies_rub": "Роzzійский рубль",
```suggestion
    "currencies_rub": "Россійский рубль",
```
[Лучше так](https://www.youtube.com/watch?v=stZRFhO_HGs)

2023-08-16 21:33 UTC, Agent47Dev commented on l10n/data/uk.json
> +    "exchangerate_inline_title": "Вартість одного ключа от кейса CS",
```suggestion
    "exchangerate_inline_title": "Вартість одного ключа від кейса CS",
```

2023-08-16 22:43 UTC, akimerslys commented on l10n/data/uk.json
> +    "currencies_rub": "Роzzійский рубль",
🥇 за кринж года

2023-08-16 22:50 UTC, akimerslys commented on l10n/data/uk.json
> +    "gun_origin_russia": "РоZZія",
Чемодан. Вокзал. Р....

2023-08-16 22:55 UTC, akimerslys commented on l10n/data/uk.json
> +        "(суперник в броне / без броні)",
ворог у броні
золотая середина

2023-08-16 22:56 UTC, akimerslys commented on l10n/data/uk.json
> +        "[‎](https://telegra.ph/Detalnij-opis-08-14)ℹ️ Цей бот розроблений каналом @INCS2. Його код можна знайти за цим посиланням [GitHub](https://github.com/aquaismissing/INCS2bot).",
👍

2023-08-16 22:57 UTC, akimerslys commented on l10n/data/uk.json
> +    "bot_feedback_text": "💬 Будь ласка напишіть нам ваші побажання та проблеми цього бота.",
"💬 Будь ласка, розповідь про ваші побажання чи проблеми, з якими ви зіткнулися під час використання бота." 
твоє, але троху фіксед

2023-08-16 22:59 UTC, akimerslys commented on l10n/data/uk.json
> +        "Цей бот використовується для отримання інформації про стан серверів та перевірки онлайну Counter-Strike: Global Offensive та багато іншого.",
👍

2023-08-17 08:57 UTC, SyberiaK commented on l10n/data/uk.json
> +    "currencies_rub": "Роzzійский рубль",
:/

2023-08-17 11:38 UTC, SyberiaK commented
Список ключей пополнился:
```json
    "user_gamestats_generated_with": "Cгенерировано с помощью",
    "user_gamestats_header": "📊 Общая игровая статистика:",
    "user_gamestats_playtime": "Время в игре (матчмейкинг):",
    "user_gamestats_kills": "Убийств:",
    "user_gamestats_deaths": "Смертей:",
    "user_gamestats_kd_ratio": "Соотношение У/С:",
    "user_gamestats_matches_played": "Матчей сыграно:",
    "user_gamestats_matches_won": "Матчей выиграно:",
    "user_gamestats_win_percentage": "Процент побед:",
    "user_gamestats_rounds_played": "Раундов сыграно:",
    "user_gamestats_pistol_rounds_won": "Пистолетных раундов выиграно:",
    "user_gamestats_aim_stats": "🔫 Статистика стрельбы:",
    "user_gamestats_shots": "Выстрелов:",
    "user_gamestats_hits": "Попаданий:",
    "user_gamestats_aim_accuracy": "Точность стрельбы:",
    "user_gamestats_hs_percentage": "Процент попаданий в голову:",
    "user_gamestats_maps_stats": "🗺️ Статистика карт:",
    "user_gamestats_best_map": "Лучшая карта:",
    "user_gamestats_misc_stats": "🔰 Прочее:",
    "user_gamestats_mvp_rewards": "Наград СЦИ:",
    "user_gamestats_total_income": "Денег заработано:",
    "user_gamestats_hostages_rescued": "Заложников спасено:",
    "user_gamestats_weapons_dropped": "Оружий выброшено:",
    "user_gamestats_windows_broken": "Разбито окон:",
    "user_gamestats_dealt_damage": "Нанесено урона:",
    "user_gamestats_bombs_planted": "Бомб установлено:",
    "user_gamestats_bombs_defused": "Бомб обезврежено:",
    "user_gamestats_knife_kills": "Убийств ножом:",
    "user_gamestats_grenade_kills": "Убийств гранатой:",
    "user_gamestats_molotov_kills": "Убийств «коктейлем Молотова»:",
    "user_gamestats_zeus_shots": "Выстрелов из Zeus:",
    "user_gamestats_zeus_kills": "Убийств из Zeus:",
    "user_gamestats_zeus_aim_accuracy": "Точность попаданий из Zeus:",
    "user_gamestats_knife_fights_won": "Выиграно поедников на ножах:",
    "user_gamestats_enemy_weapon_kills": "Убийств из вражеского оружия:",
    "user_gamestats_flashed_enemies_kills": "Ослепленных врагов убито:",
    "user_gamestats_scoped_snipers_kills": "Убито прицелившихся снайперов:",
    "user_gamestats_gun_stats": "🔫 Статистика оружий:",
    "user_gamestats_pistols_stats": "🔫 Статистика пистолетов:",
    "user_gamestats_heavy_stats": "🔫 Статистика тяжёлых оружий:",
    "user_gamestats_smgs_stats": "🔫 Статистика пистолетов-пулемётов:",
    "user_gamestats_rifles_stats": "🔫 Статистика штурмовых винтовок:",
    "user_gamestats_snipers_stats": "🔫 Статистика снайперских винтовок:",
```
Здесь все ключевые строки, которые использовались в `user_gamestats_text`, остальное вынесли в отдельный файл, чтобы было проще переводить.
Можешь просто вставить эти строки в файл и перевести их (перенести строки из `user_gamestats_text`).

2023-08-18 18:09 UTC, SyberiaK commented
Всё круто, ждём контрольной проверки от @Agent47Dev и можно мерджить.

2023-08-18 22:06 UTC, Agent47Dev approved these changes

2023-08-19 10:46 UTC, merged